"""Prescription PDF renderer for Online VaidyaJi.

Generates a clean, professional single-page A4 PDF from an appointment's
prescription record. Uses ReportLab (no external system deps).

The PDF is streamed inline so mobile clients can render it in-app, and can
also be forced as an attachment when downloading.
"""
import io
import logging
from datetime import datetime
from typing import Dict, Any, Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    BaseDocTemplate, Frame, PageTemplate, Paragraph, Spacer, Table, TableStyle,
)

logger = logging.getLogger(__name__)

BRAND = colors.HexColor("#0F4C36")     # Deep Forest Green
ACCENT = colors.HexColor("#D9663D")    # Terracotta
INK = colors.HexColor("#1c2b23")
MUTED = colors.HexColor("#7b6b53")
BG = colors.HexColor("#faf6ee")


def _fmt_dt(iso_str: Optional[str]) -> str:
    if not iso_str:
        return "—"
    try:
        dt = datetime.fromisoformat(iso_str.replace("Z", ""))
        return dt.strftime("%d %b %Y · %I:%M %p")
    except Exception:
        return iso_str or "—"


def render_prescription_pdf(appt: Dict[str, Any], *, doctor: Dict[str, Any] | None = None,
                            patient: Dict[str, Any] | None = None) -> bytes:
    """Return PDF bytes for an appointment's `prescription` payload."""
    rx = appt.get("prescription") or {}
    if not rx:
        raise ValueError("Appointment has no prescription to render")

    buf = io.BytesIO()

    def _header(canvas, doc):
        canvas.saveState()
        # Top brand strip
        canvas.setFillColor(BRAND)
        canvas.rect(0, A4[1] - 22 * mm, A4[0], 22 * mm, fill=1, stroke=0)
        canvas.setFillColor(colors.white)
        canvas.setFont("Helvetica-Bold", 14)
        canvas.drawString(18 * mm, A4[1] - 12 * mm, "ॐ  Online VaidyaJi")
        canvas.setFont("Helvetica", 9)
        canvas.drawString(
            18 * mm, A4[1] - 17.5 * mm,
            "Verified AYUSH practitioners · Digital prescription",
        )
        canvas.setFillColor(colors.HexColor("#ffe082"))
        canvas.setFont("Helvetica-Bold", 8)
        canvas.drawRightString(
            A4[0] - 18 * mm, A4[1] - 12 * mm,
            f"Rx # {(appt.get('id') or '')[:8].upper()}",
        )

        # Footer
        canvas.setFillColor(MUTED)
        canvas.setFont("Helvetica", 7.5)
        canvas.drawString(
            18 * mm, 12 * mm,
            "Generated by Online VaidyaJi · onlinevaidhyaji.com",
        )
        canvas.drawRightString(
            A4[0] - 18 * mm, 12 * mm,
            f"Printed: {datetime.utcnow().strftime('%d %b %Y · %H:%M UTC')}",
        )
        # A faint watermark so photocopies are obviously secondary
        canvas.setFillColorRGB(0.86, 0.83, 0.75, alpha=0.35)
        canvas.setFont("Helvetica-Bold", 60)
        canvas.saveState()
        canvas.translate(A4[0] / 2, A4[1] / 2)
        canvas.rotate(30)
        canvas.drawCentredString(0, 0, "ONLINE VAIDYAJI")
        canvas.restoreState()
        canvas.restoreState()

    frame = Frame(
        18 * mm, 18 * mm, A4[0] - 36 * mm, A4[1] - 46 * mm,
        showBoundary=0,
    )
    doctemplate = BaseDocTemplate(
        buf, pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm,
        topMargin=28 * mm, bottomMargin=20 * mm,
        title="Online VaidyaJi Prescription",
        author="Online VaidyaJi",
    )
    doctemplate.addPageTemplates([PageTemplate(id="main", frames=[frame], onPage=_header)])

    ss = getSampleStyleSheet()
    styles = {
        "h1":  ParagraphStyle("h1", parent=ss["Heading1"], textColor=BRAND, fontSize=16, spaceAfter=2),
        "h2":  ParagraphStyle("h2", parent=ss["Heading2"], textColor=ACCENT, fontSize=12, spaceBefore=10, spaceAfter=4),
        "lbl": ParagraphStyle("lbl", parent=ss["Normal"], textColor=MUTED, fontSize=8, leading=10),
        "val": ParagraphStyle("val", parent=ss["Normal"], textColor=INK, fontSize=10.5, leading=13),
        "sig": ParagraphStyle("sig", parent=ss["Normal"], textColor=INK, fontSize=10, leading=14),
        "note": ParagraphStyle("note", parent=ss["Normal"], textColor=MUTED, fontSize=8.5, leading=11),
    }

    story = []

    # Doctor / Patient meta table
    doc_name = (doctor or {}).get("name") or appt.get("doctor_name") or rx.get("author_name") or "AYUSH Doctor"
    doc_qual = (doctor or {}).get("qualification") or "AYUSH Practitioner"
    doc_specialty = (doctor or {}).get("specialty") or appt.get("doctor_specialty") or "Ayurveda"
    pt_name = (patient or {}).get("name") or appt.get("patient_name") or "Patient"
    pt_id = ((patient or {}).get("id") or appt.get("patient_id") or "")[:8].upper()
    visit_dt = _fmt_dt(appt.get("slot") or rx.get("written_at"))

    meta = [
        [Paragraph("<b>Doctor</b>", styles["lbl"]),
         Paragraph("<b>Patient</b>", styles["lbl"])],
        [Paragraph(f"{doc_name}", styles["val"]),
         Paragraph(f"{pt_name}", styles["val"])],
        [Paragraph(f"{doc_qual} · {doc_specialty}", styles["note"]),
         Paragraph(f"Patient ID: {pt_id or '—'}", styles["note"])],
        [Paragraph(f"<b>Consultation:</b> {visit_dt}", styles["note"]),
         Paragraph(f"<b>Written:</b> {_fmt_dt(rx.get('written_at'))}", styles["note"])],
    ]
    meta_tbl = Table(meta, colWidths=[(A4[0] - 36 * mm) / 2] * 2)
    meta_tbl.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    story.append(meta_tbl)
    story.append(Spacer(1, 8))

    # ─── Diagnosis + notes ──────────────────────────────────────────────
    if rx.get("diagnosis"):
        story.append(Paragraph("Diagnosis / Assessment", styles["h2"]))
        story.append(Paragraph(rx["diagnosis"], styles["val"]))

    # ─── Medicines table ────────────────────────────────────────────────
    structured = rx.get("medicines_structured") or []
    if structured:
        story.append(Paragraph("℞ Prescribed Medicines", styles["h2"]))
        rows = [["#", "Medicine", "Dosage", "Frequency", "Duration", "Notes"]]
        for i, m in enumerate(structured, 1):
            rows.append([
                str(i),
                m.get("name", ""),
                m.get("dosage", ""),
                m.get("frequency", ""),
                m.get("duration", ""),
                m.get("instructions", ""),
            ])
        med_tbl = Table(
            rows,
            colWidths=[8 * mm, 45 * mm, 25 * mm, 30 * mm, 25 * mm, 40 * mm],
        )
        med_tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), BRAND),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 9),
            ("FONTSIZE", (0, 1), (-1, -1), 9),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#d9d3c1")),
            ("BACKGROUND", (0, 1), (-1, -1), colors.white),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, BG]),
        ]))
        story.append(med_tbl)
    elif rx.get("medicines"):
        story.append(Paragraph("℞ Prescribed Medicines", styles["h2"]))
        # Preserve line breaks
        med_text = (rx.get("medicines") or "").replace("\n", "<br/>")
        story.append(Paragraph(med_text, styles["val"]))

    # ─── Advice + lifestyle ─────────────────────────────────────────────
    if rx.get("advice"):
        story.append(Paragraph("Lifestyle & Ahara-Vihara advice", styles["h2"]))
        story.append(Paragraph(rx["advice"].replace("\n", "<br/>"), styles["val"]))

    if rx.get("follow_up_at"):
        story.append(Paragraph("Follow-up", styles["h2"]))
        story.append(Paragraph(
            f"Please return for a follow-up on <b>{_fmt_dt(rx['follow_up_at'])}</b>.",
            styles["val"],
        ))

    # ─── Signature ──────────────────────────────────────────────────────
    story.append(Spacer(1, 22))
    story.append(Paragraph(
        f"<b>{doc_name}</b><br/>"
        f"<font color='#7b6b53'>{doc_qual} · {doc_specialty}</font><br/>"
        f"<font color='#7b6b53'>Registration verified on Online VaidyaJi</font>",
        styles["sig"],
    ))

    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "This is a digitally issued prescription. Please cross-check dosages "
        "with the dispensing pharmacist. Do not share your prescription publicly.",
        styles["note"],
    ))

    doctemplate.build(story)
    return buf.getvalue()
